<?php

namespace Database\Seeders;

use App\Models\TourPackage;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        User::updateOrCreate(['email' => 'admin@lingayen.test'], ['name' => 'Admin User', 'password' => Hash::make('password'), 'is_admin' => true]);
        User::updateOrCreate(['email' => 'tourist@lingayen.test'], ['name' => 'Tourist User', 'password' => Hash::make('password'), 'is_admin' => false]);

        $packages = [
            [
                'title' => 'VillaMar Ramos Resort',
                'category' => 'Resort',
                'stars' => 4,
                'description' => 'Situated in Lingayen, a few steps from Lingayen Beach, VillaMar Ramos Resort features accommodation with a garden, free private parking, a terrace, family-friendly outdoor spaces, and pool facilities for guests looking for a relaxing stay near the beach.',
                'location' => 'Lingayen',
                'distance' => '1.9 km from centre',
                'beach_info' => '50 m from beach',
                'duration' => '1 Night',
                'price' => 2500,
                'slots' => 20,
                'image_url' => 'images/places/villamar-ramos-resort.jpg',
                'review_score' => 2.0,
                'review_count' => 3,
                'amenities' => 'Beach nearby,Swimming pool,Free private parking,Garden,Terrace,Family rooms',
            ],
            [
                'title' => 'Beachfront Glamping with Mini Pool Exclusive Property',
                'category' => 'Glamping',
                'stars' => 3,
                'description' => 'Featuring air-conditioned accommodation with a private pool, sea view and a balcony, Beachfront Glamping with Mini Pool Exclusive Property is located in Lingayen. This unique accommodation is ideal for couples, friends, and families who want a cozy beachside glamping experience.',
                'location' => 'Lingayen',
                'distance' => '2.4 km from centre',
                'beach_info' => 'Beachfront',
                'duration' => '1 Night',
                'price' => 4200,
                'slots' => 10,
                'image_url' => 'images/places/beachfront-glamping-mini-pool.jpg',
                'review_score' => 6.0,
                'review_count' => 14,
                'amenities' => 'Beachfront,Private pool,Sea view,Balcony,Air-conditioned rooms,Mini pool',
            ],
            [
                'title' => 'Bergamo Hotel Lingayen',
                'category' => 'Hotel',
                'stars' => 4,
                'description' => 'Situated in Lingayen, 2.2 km from Lingayen Beach, Bergamo Hotel Lingayen features accommodation with a fitness centre, free private parking, a restaurant and a bar. It is a convenient hotel option near the town centre for visitors who want comfort and easy access to local destinations.',
                'location' => 'Lingayen',
                'distance' => '200 m from centre',
                'beach_info' => '1.8 km from beach',
                'duration' => '1 Night',
                'price' => 3200,
                'slots' => 18,
                'image_url' => 'images/places/bergamo-hotel-lingayen.jpg',
                'review_score' => 7.4,
                'review_count' => 53,
                'amenities' => 'Fitness centre,Free private parking,Restaurant,Bar,Beach nearby,Hotel rooms',
            ],
            [
                'title' => 'El Puerto Marina Beach Resort & Vacation Club',
                'category' => 'Beach Resort',
                'stars' => 3,
                'description' => 'Set on the unspoilt sands of Lingayen’s coast, El Puerto Marina Beach Resort and Vacation Club offers beachfront accommodation with thatched roofs. It features an outdoor pool, a spa, tropical surroundings, and relaxing resort facilities for vacation stays.',
                'location' => 'Lingayen',
                'distance' => '2.4 km from centre',
                'beach_info' => 'Beachfront',
                'duration' => '1 Night',
                'price' => 3800,
                'slots' => 25,
                'image_url' => 'images/places/el-puerto-marina-beach-resort.jpg',
                'review_score' => 6.3,
                'review_count' => 24,
                'amenities' => 'Beachfront,Outdoor pool,Spa,Restaurant,Vacation club,Tropical garden',
            ],
            [
                'title' => 'Capandanan Cottages',
                'category' => 'Cottage',
                'stars' => 0,
                'description' => 'A recently renovated holiday home located in Lingayen, Capandanan Cottages features a garden. This property offers access to a terrace and free private parking, making it suitable for guests looking for a quiet cottage-style stay.',
                'location' => 'Lingayen, Capandanan',
                'distance' => '4.6 km from centre',
                'beach_info' => 'Garden stay',
                'duration' => '1 Night',
                'price' => 1800,
                'slots' => 8,
                'image_url' => 'images/places/capandanan-cottages.jpg',
                'review_score' => 7.0,
                'review_count' => 2,
                'amenities' => 'Garden,Terrace,Free private parking,Holiday home,Quiet location,Cottage stay',
            ],
            [
                'title' => 'River Palm Hotel and Resort powered by Cocotel',
                'category' => 'Hotel and Resort',
                'stars' => 3,
                'description' => 'Located in Bugallon, 46 km from Hundred Islands National Park, River Palm Hotel and Resort powered by Cocotel provides accommodation with an outdoor swimming pool, free private parking, a garden and a restaurant.',
                'location' => 'Bugallon',
                'distance' => '3.9 km from Lingayen',
                'beach_info' => 'Near river area',
                'duration' => '1 Night',
                'price' => 3500,
                'slots' => 20,
                'image_url' => 'images/places/river-palm-hotel-and-resort.jpg',
                'review_score' => 9.1,
                'review_count' => 34,
                'amenities' => 'Outdoor swimming pool,Free private parking,Garden,Restaurant,River view,Family rooms',
            ],
            [
                'title' => "Tres Marias' Resort",
                'category' => 'Resort',
                'stars' => 0,
                'description' => "Situated in Binmaley, 400 metres from Binmaley Beach, Tres Marias' Resort features accommodation with an outdoor swimming pool, free private parking, a garden and a shared lounge.",
                'location' => 'Binmaley',
                'distance' => '3.4 km from Lingayen',
                'beach_info' => '350 m from beach',
                'duration' => '1 Night',
                'price' => 2800,
                'slots' => 15,
                'image_url' => 'images/places/tres-marias-resort.jpg',
                'review_score' => 8.0,
                'review_count' => 12,
                'amenities' => 'Outdoor swimming pool,Free private parking,Garden,Shared lounge,Beach nearby,Family rooms',
            ],
            [
                'title' => "Tres Marias' Garden Resort, Resto and Sports Bar",
                'category' => 'Garden Resort',
                'stars' => 0,
                'description' => "Tres Marias' Garden Resort, Resto and Sports Bar is situated in Binmaley, 400 metres from Binmaley Beach. Some rooms at the property have a terrace with pool view.",
                'location' => 'Binmaley',
                'distance' => '3.4 km from Lingayen',
                'beach_info' => '350 m from beach',
                'duration' => '1 Night',
                'price' => 3000,
                'slots' => 18,
                'image_url' => 'images/places/tres-marias-garden-resort-resto-sports-bar.jpg',
                'review_score' => 8.3,
                'review_count' => 18,
                'amenities' => 'Pool view,Terrace,Restaurant,Sports bar,Garden,Beach nearby',
            ],
            [
                'title' => 'Villa Leonida Resort',
                'category' => 'Resort',
                'stars' => 1,
                'description' => 'Featuring pool views, Villa Leonida Resort features accommodation with a garden, a terrace and barbecue facilities, around 48 km from Hundred Islands National Park.',
                'location' => 'Bugallon',
                'distance' => '9.1 km from Lingayen',
                'beach_info' => 'Garden stay',
                'duration' => '1 Night',
                'price' => 2500,
                'slots' => 12,
                'image_url' => 'images/places/villa-leonida-resort.jpg',
                'review_score' => 7.7,
                'review_count' => 10,
                'amenities' => 'Pool view,Garden,Terrace,Barbecue facilities,Free parking,Family rooms',
            ],
            [
                'title' => 'Buddha Resort by Cocotel',
                'category' => 'Resort',
                'stars' => 3,
                'description' => 'Set in Bugallon and with Hundred Islands National Park reachable within 42 km, Buddha Resort by Cocotel offers a garden, non-smoking rooms, free WiFi and a restaurant.',
                'location' => 'Bugallon',
                'distance' => '6.2 km from Lingayen',
                'beach_info' => 'Near Hundred Islands route',
                'duration' => '1 Night',
                'price' => 3200,
                'slots' => 16,
                'image_url' => 'images/places/buddha-resort.jpg',
                'review_score' => 8.2,
                'review_count' => 5,
                'amenities' => 'Garden,Non-smoking rooms,Free WiFi,Restaurant,Swimming pool,Free parking',
            ],
        ];

        foreach ($packages as $package) {
            TourPackage::updateOrCreate(['title' => $package['title']], $package);
        }
    }
}